name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      denops_version:
        description: Denops version
        required: false
        default: "v5.0.0"  # or "main"

jobs:
  build:
    permissions:
      packages: write
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get DENOPS_VERSION
        id: vars
        run: |
          if [[ -z "${{ github.event.inputs.denops_version }}" ]]; then
            echo '::set-output name=DENOPS_VERSION::v5.0.0'
          else
            echo '::set-output name=DENOPS_VERSION::${{ github.event.inputs.denops_version }}'
          fi
        shell: bash
      - run: make DENOPS_VERSION=${{ steps.vars.outputs.DENOPS_VERSION }} build

      - name: Push to ghcr.io
        env:
          DENOPS_VERSION: ${{ steps.vars.outputs.DENOPS_VERSION }}
        shell: bash
        run: |
          if [[ ${{ env.DENOPS_VERSION }} == v* ]]; then
            # Full version string
            make DOCKER_TAG=${{ env.DENOPS_VERSION }} push
            # vX.Y.Z -> vX (major only)
            export DOCKER_TAG_MAJOR=$(echo ${{ env.DENOPS_VERSION }} | sed -r 's/(v[0-9]+)(\.[0-9]+)(\.[0-9]+)/\1/')
            make DOCKER_TAG=$DOCKER_TAG_MAJOR push
            # vX.Y.Z -> vX.Y (major and minor)
            export DOCKER_TAG_MINOR=$(echo ${{ env.DENOPS_VERSION }} | sed -r 's/(v[0-9]+)(\.[0-9]+)(\.[0-9]+)/\1/\2')
            make DOCKER_TAG=$DOCKER_TAG_MINOR push
          fi
          make push
